# Generated by Django 4.0.4 on 2022-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_name', models.CharField(max_length=255)),
                ('purchaser', models.CharField(max_length=255)),
                ('perfume_price', models.IntegerField(max_length=155)),
                ('perfume_edition', models.CharField(max_length=255)),
                ('perfume_size', models.IntegerField(max_length=55)),
                ('perfume_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
