# Generated by Django 4.0.4 on 2022-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_alter_customuser_item_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
